version: '3.8'

services:
  web:
    build: .
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
    expose:
      - "8000"
    depends_on:
      - redis
    volumes:
      - ./app.db:/app/app.db
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx
    entrypoint: "
      sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
    "
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  letsencrypt:
