name: Build and deploy Python app to Azure Web App - imperial

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          set-safe-directory: 'true'

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Fix root files for Azure
        run: |
          cp fastapi-mobile-app/requirements.txt .
          echo "web: uvicorn fastapi-mobile-app.main:app --host 0.0.0.0 --port \${PORT:-8000} --workers 1" > Procfile

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DD164541268243B3842563E45DB21044 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C49D636A06084AF0A8ABC17506B0758F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DA4F79CD9A474A8D9EA4A05228308685 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'imperial'
          slot-name: 'Production'
